### ISSUE TITLE
Na página Downloads - Esconder a Categoria: IMAGENS

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#13]
Para não fazer download desta categoria nesta página.
Portanto "Tornar Invisível a categoria:" Imagens na seção de DOWNLOADS.

A seção Imagens serve somente para a parte interna das páginas.
Se quiser disponibilizar downloads de imagens coloco em "Fotos de Produtos"

**Comment by lucianotonet** [comment]
Eu fiz com que só apareça arquivos que forem atribuídos à uma categoria.
Para as imagens do site, não atribua categorias e elas não aparecerão.

Eu excluí a categoria "imagens":
![image](https://cloud.githubusercontent.com/assets/2693019/14901634/d10bd10e-0d6c-11e6-9c37-2264b2ff82b0.png)

Se for necessário, pode fazer como falou e criar uma nova categoria "Fotos de Produtos".
