### ISSUE TITLE
Acertar alinhamento de ícones - 2 colunas 

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#14]
http://demos.agenciamav.com.br/sparkag.com.br/a-spark/

Colocar de forma em duas colunas (2 principios)... e acertar o alinhamento dos ícones na mesma linha do subtitulo.

**Comment by lucianotonet** [comment]
Corrigido.
Como se trata de conteúdo inserido pelo painel administrativo, o alinhamento fica salvo em banco de dados, não tendo ligação com o código-fonte do site.

![image](https://cloud.githubusercontent.com/assets/2693019/14901442/bb7c07b0-0d6b-11e6-992b-000860ce9bd8.png)

Obs.
Como é uma diagramação complexa, talvez seja mais recomendado criarmos esta página estática, ou seja, com o conteúdo direto no código-fonte.
