### ISSUE TITLE
Rodapé da página

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#15]
no lado inferior direito da página: temos a frase grande: DESENVOLVEMOS PROJETOS DE CONSULTORIA E SOLUÇÕES LOGÍSTICAS SOB MEDIDA (???)

Colocar:
DESENVOLVEMOS PROJETOS DE CONSULTORIA E SOLUÇÕES INTRALOGÍSTICAS SOB MEDIDA.

E ai o link saiba mais.... vai para a página --> CONSULTORIA

**Comment by ghost** [comment]
Ou melhor:

DESENVOLVEMOS PROJETOS DE CONSULTORIA COM SOLUÇÕES INTEGRADAS E PERSONALIZADAS PARA INTRALOGÍSTICA.

**Comment by lucianotonet** [comment]
Por coincidência estou mexendo exatamente nisso.
Eu tinha pensado numa outra solução mais dinâmica (ver na issue #11 )

**Comment by lucianotonet** [comment]
Bom, testei e não deu muito certo:
No rodapé ficou bom:
![image](https://cloud.githubusercontent.com/assets/2693019/14902876/e78586f8-0d73-11e6-9bea-05b3acda33ed.png)

Mas ferrou com as news, pois os sticky post SEMPRE vão aparecer antes q os outros:
![image](https://cloud.githubusercontent.com/assets/2693019/14902839/b895d6fe-0d73-11e6-8502-2737cc6bff7d.png)

Vou fazer com uma frase estática mesmo então, com um link para CONSULTORIA.
