### ISSUE TITLE
Solicite uma ligação fica igual ou parecido com o Fale Conosco

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#19]

**Comment by ghost** [comment]
Ou seja fazer igual ou somente mudar algumas palavras....

**Comment by lucianotonet** [comment]
#10

**Comment by ghost** [comment]
Solicite uma Ligação 

Solicite uma COnsultoria 

deve ter um formulario igual a Fale Conosco... 

Somente muda o ASSUNTO do email que envia.... 

Em 26/12/2016 19:02, Luciano Tonet escreveu: 

> Closed #19 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

  

Links:
------
[1] https://github.com/agenciamav/spark-wp-theme/issues/19
[2]
https://github.com/agenciamav/spark-wp-theme/issues/19#event-905268934
[3]
