### ISSUE TITLE
Adicionar a imagem de assinatura de email - que tinha no antigo site

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#28]
<a class="clink logo-container" style="text-decoration: none" href="http://www.sparkag.com.br"> <img class="sig-logo" src="http://sparkag.com.br/mailsignature/images/logo.png" alt="Spark AG" width="80" height="80" border="0"></a>

**Comment by ghost** [comment]
src=http://sparkag.com.br/mailsignature/images/logo.png

**Comment by lucianotonet** [comment]
Gerador de assinatura restaurado!
http://sparkag.com.br/mailsignature/

![image](https://cloud.githubusercontent.com/assets/2693019/15063173/112a1636-131e-11e6-8dc2-c2b71dbaac18.png)
