### ISSUE TITLE
Na página de cada Produto - seção Downloads

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#30]
Esta mostrando o nome do arquivo... e seria necessário a Descrição (pois fica feio...)

**Comment by lucianotonet** [comment]
Corrigido. Agora ele exibe o título e não mais o nome do arquivo.

![image](https://cloud.githubusercontent.com/assets/2693019/15063476/ffc78100-1320-11e6-8611-f57c34418ac3.png)
