### ISSUE TITLE
No site não esta setado que LINGUA ele é padrão, porem lembrar que vou fazer ele em ESPANHOL no futuro tambem

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#33]

**Comment by lucianotonet** [comment]
OK. Vamos implementar este plugin... https://wpml.org/pt-br/ . Talvez seja necessário algum ajuste no site pra funcionar tudo certo.
Adicionado nova Issue para controle de tarefas aqui #42. Essa será fechada.
