### ISSUE TITLE
SEO:

### ISSUE THREAD

**Issue by ghost** [agenciamav/spark-wp-theme#37]
Primary Errors:
 Verify the target of the Canonical
 URL's with ssl redirect to a different page.
 Headlines are in a wrong order or missing a hierarchy
 Some images do not have an Alt Attribute

Secondary Warnings:
 Add more info to the Title
 The Description is quite short
 IP does not redirect to homepage
 There are too many JavaScript files embedded
 Remove inline CSS
 Move inline JavaScript to a central script file
 There are too many CSS files embedded
 Define the language of the content
 Disable the server signature on your webserver
 Raise the Max-Age Parameter of your Browser Cache Settings
 Some images lack width or height attributes
 Get rid of unnecessary source codes
 Add an Touch Icon for mobile bookmarks

**Comment by lucianotonet** [comment]
Autoexplicativo
